name: manual-CI
on: [workflow_dispatch]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Copy readme and license
      run: |
        cp "$PKG_ROOT"/"$LICENSE_FILE" ./
        git add "$LICENSE_FILE"
        mkdir -p docs
        cp "$PKG_ROOT"/"$README_FILE" ./docs/
        git add ./docs/"$README_FILE"
        git commit -m "docs: updated readme and license" --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" || echo "No changes to commit"
      env:
        PKG_ROOT: Packages/LocalStorage
        LICENSE_FILE: LICENSE.md
        README_FILE: README.md
    - name: Semantic release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2.5.3
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found
        git subtree split -P "$PKG_ROOT" -b upm
        git checkout upm
        git push -f -u origin upm
      env:
        PKG_ROOT: Packages/LocalStorage
    - name: Create upm git tag
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        git tag $TAG upm
        git push origin --tags
      env:
        TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
